# // Pygstudio template file created by pygstudio script (Version 1.0)
# ? You are free to edit this script
# ! This is a stub file for save.py

from typing import Dict, List, Union

JsonValue = Union[
    Dict[str, "JsonValue"], List["JsonValue"], str, bool, int, float, None
]

SaveFolder: str

def save_file_raw(filename: str, data: Union[str, bytes], mode: str = "wt") -> None: ...
def save_file(filename: str, data: JsonValue) -> None: ...
def read_file_raw(filename: str, mode: str = "rt") -> Union[str, bytes]: ...
def read_file(filename: str) -> JsonValue: ...
def save(data: JsonValue): ...
def read(): ...


# * Code that encrypts your saves (Uncomment them if you use it)
# def save_file_encrypted(filename: str, data: JsonValue) -> None: ...
# def read_file_encrypted(filename: str) -> JsonValue: ...
